import {
  css,
  cpp,
  express,
  git,
  github,
  html,
  javascript,
  mongodb,
  nextjs,
  nodejs,
  php,
  python,
  react,
  redux,
  sass,
  contact,
  linkedin,
  pricewise,
  threads,
  car,
  snapgram,
  estate,
  summiz,
  typescript,
  angular,
  vuejs,
  bootstrap,
  babel,
  webpack,
  tailwindcss,
  graphql,
  mysql,
  mariadb,
  pandas,
  seaborn,
  matplotlib,
  chartjs,
  docker,
  bash,
  heroku,
  firebase,
  django,
  laravel,
  figma,
  illustrator,
  photoshop,
  postman,
  xd,
  linux,
  arduino,
  StandardForce,
  LTU,
  earthday,
  BeingArtifexLogo,
} from "../assets/icons";

export const skills = [
  { imageUrl: cpp, name: "C++", category: "Programming Languages" },
  {
    imageUrl: javascript,
    name: "JavaScript",
    category: "Programming Languages",
  },
  { imageUrl: php, name: "PHP", category: "Programming Languages" },
  { imageUrl: python, name: "Python", category: "Programming Languages" },
  {
    imageUrl: typescript,
    name: "TypeScript",
    category: "Programming Languages",
  },
  { imageUrl: angular, name: "Angular", category: "Frontend Development" },
  { imageUrl: react, name: "React", category: "Frontend Development" },
  { imageUrl: redux, name: "Redux", category: "Frontend Development" },
  { imageUrl: vuejs, name: "Vue.js", category: "Frontend Development" },
  { imageUrl: bootstrap, name: "Bootstrap", category: "Frontend Development" },
  { imageUrl: css, name: "CSS3", category: "Frontend Development" },
  { imageUrl: babel, name: "Babel", category: "Frontend Development" },
  { imageUrl: webpack, name: "Webpack", category: "Frontend Development" },
  { imageUrl: html, name: "HTML5", category: "Frontend Development" },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    category: "Frontend Development",
  },
  { imageUrl: sass, name: "Sass", category: "Frontend Development" },
  { imageUrl: nodejs, name: "Node.js", category: "Backend Development" },
  { imageUrl: express, name: "Express", category: "Backend Development" },
  { imageUrl: graphql, name: "GraphQL", category: "Backend Development" },
  { imageUrl: mongodb, name: "MongoDB", category: "Database" },
  { imageUrl: mysql, name: "MySQL", category: "Database" },
  { imageUrl: mariadb, name: "MariaDB", category: "Database" },
  { imageUrl: pandas, name: "Pandas", category: "AI/ML" },
  { imageUrl: seaborn, name: "Seaborn", category: "AI/ML" },
  { imageUrl: matplotlib, name: "Matplotlib", category: "Data Visualization" },
  { imageUrl: chartjs, name: "Chart.js", category: "Data Visualization" },
  { imageUrl: docker, name: "Docker", category: "DevOps" },
  { imageUrl: bash, name: "Bash", category: "DevOps" },
  { imageUrl: heroku, name: "Heroku", category: "BaaS" },
  { imageUrl: firebase, name: "Firebase", category: "BaaS" },
  { imageUrl: django, name: "Django", category: "Fullstack Framework" },
  { imageUrl: laravel, name: "Laravel", category: "Fullstack Framework" },
  { imageUrl: nextjs, name: "NextJS", category: "Fullstack Framework" },
  { imageUrl: figma, name: "Figma", category: "Software" },
  { imageUrl: illustrator, name: "Illustrator", category: "Software" },
  { imageUrl: photoshop, name: "Photoshop", category: "Software" },
  { imageUrl: postman, name: "Postman", category: "Software" },
  { imageUrl: xd, name: "Adobe XD", category: "Software" },
  { imageUrl: git, name: "Git", category: "Other" },
  { imageUrl: linux, name: "Linux", category: "Other" },
  { imageUrl: arduino, name: "Arduino", category: "Other" },
];

const options = { year: "numeric", month: "short" };
const currentDate = new Date();
const formattedDate = currentDate.toLocaleDateString("en-US", options);
export const experiences = [
  {
    title: "Software Development Engineer (Full Time)",
    company_name: "Standard Force Corporation, Japan",
    icon: StandardForce,
    iconBg: "#90e0ef",
    date: `Aug 2023 - ${formattedDate}`,
    points: [
      "Developed a dashboard using React.js and Node.js, improving data visualization and decision-making.",
      "Integrated critical business parameters, boosting operational efficiency.",
      "Improved the Laravel-based business management system, optimizing overseas operations and enhancing overall business processes.",
    ],
  },
  {
    title: "Fullstack Web Developer (Intern)",
    company_name: "LTU Corporation, Japan",
    icon: LTU,
    iconBg: "#b7e4c7",
    date: "May 2023 - Aug 2023",
    points: [
      "Developed a dashboard using React.js and Node.js, improving data visualization and decision-making.",
      "Integrated critical business parameters, boosting operational efficiency.",
      "Improved the Laravel-based business management system, optimizing overseas operations and enhancing overall business processes.",
    ],
  },
  {
    title: "Team Head Mentor (Graphics and WebDev)",
    company_name: "Being Artifex",
    icon: BeingArtifexLogo,
    iconBg: "#accbe1",
    date: "March 2021 - July 2021",
    points: [
      "Provided mentorship to over 1,000 students during the nationwide skillathon organized by BeingArtifex and IIT(ISM) Dhanbad.",
    ],
  },
  {
    title: "Web Developer & UI/UX (Freelance)",
    company_name: "EarthDay",
    icon: earthday,
    iconBg: "#e1e8f0",
    date: "May 2021 - July 2021",
    points: [
      "Developed and improved the website for the early startup 'EarthDay' as a web developer.",
      "Utilized skills in web development and UI/UX design to enhance the overall user experience of the site.",
    ],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/i-m-abbhay",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin, // Replace 'linkedin_icon' with actual icon path if available
    link: "https://www.linkedin.com/in/imabbhay/",
  },
];

export const projects = [
  {
    iconUrl: pricewise,
    theme: "btn-back-red",
    name: "Amazon Price Tracker",
    description:
      "Developed a web application that tracks and notifies users of price changes for products on Amazon, helping users find the best deals.",
    link: "https://github.com/adrianhajdin/pricewise",
  },
  {
    iconUrl: threads,
    theme: "btn-back-green",
    name: "Full Stack Threads Clone",
    description:
      'Created a full-stack replica of the popular discussion platform "Threads," enabling users to post and engage in threaded conversations.',
    link: "https://github.com/adrianhajdin/threads",
  },
  {
    iconUrl: car,
    theme: "btn-back-blue",
    name: "Car Finding App",
    description:
      "Designed and built a mobile app for finding and comparing cars on the market, streamlining the car-buying process.",
    link: "https://github.com/adrianhajdin/project_next13_car_showcase",
  },
  {
    iconUrl: snapgram,
    theme: "btn-back-pink",
    name: "Full Stack Instagram Clone",
    description:
      "Built a complete clone of Instagram, allowing users to share photos and connect with friends in a familiar social media environment.",
    link: "https://github.com/adrianhajdin/social_media_app",
  },
  {
    iconUrl: estate,
    theme: "btn-back-black",
    name: "Real-Estate Application",
    description:
      "Developed a web application for real estate listings, facilitating property searches and connecting buyers with sellers.",
    link: "https://github.com/adrianhajdin/projects_realestate",
  },
  {
    iconUrl: summiz,
    theme: "btn-back-yellow",
    name: "AI Summarizer Application",
    description:
      "App that leverages AI to automatically generate concise & informative summaries from lengthy text content, or blogs.",
    link: "https://github.com/adrianhajdin/project_ai_summarizer",
  },
];
